import '../models/user.dart';
import '../models/business.dart';
import '../models/category.dart';
import '../models/product.dart';
import '../models/media_asset.dart';
import '../models/collection.dart';
import '../models/contact.dart';
import '../models/inquiry.dart';
import '../models/plan.dart';

class MockDataService {
  static final User demoOwner = User(
    id: 1,
    businessId: 1,
    name: 'Rajeshbhai Patel',
    email: 'rajesh@suratsilkmills.com',
    phone: '+91 98251 23456',
    role: 'owner',
    avatarPath:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    isActive: true,
  );

  static final User demoSalesStaff = User(
    id: 2,
    businessId: 1,
    name: 'Amit Shah',
    email: 'amit@suratsilkmills.com',
    phone: '+91 98251 78901',
    role: 'sales_staff',
    isActive: true,
  );

  static final Business demoBusiness = Business(
    id: 1,
    publicId: 'biz_suratsilk2026',
    planId: 2,
    name: 'Surat Silk Mills',
    legalName: 'Surat Silk Mills Pvt Ltd',
    slug: 'surat-silk-mills',
    businessType: 'textile_wholesaler',
    ownerName: 'Rajeshbhai Patel',
    phone: '+91 98251 23456',
    whatsappNumber: '919825123456',
    email: 'sales@suratsilkmills.com',
    addressLine1:
        'Shop 402-405, 4th Floor, Millennium Textile Market, Ring Road',
    city: 'Surat',
    state: 'Gujarat',
    country: 'India',
    pincode: '395002',
    gstNumber: '24AACCS1234F1Z5',
    logoPath:
        'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=200&auto=format&fit=crop&q=80',
    primaryColor: '#0B8F5B',
    subscriptionStatus: 'active',
    storageUsedBytes: 420 * 1024 * 1024,
    settings: BusinessSettings(
      businessId: 1,
      catalogTitle: "Surat Silk Mills • Today's Wholesale Drop",
      catalogDescription:
          "Exclusive Georgette, Dola Silk Sarees & Designer Kurtis direct from Surat manufacturer. Ready stock available for dispatch.",
      defaultCurrency: 'INR',
      showPricesPublicly: true,
      allowGuestInquiry: true,
      watermarkEnabled: true,
      watermarkText: 'Surat Silk Mills',
    ),
  );

  static final List<Category> demoCategories = [
    Category(
      id: 1,
      businessId: 1,
      name: 'Saree Collection',
      slug: 'saree',
      sortOrder: 1,
    ),
    Category(
      id: 2,
      businessId: 1,
      name: 'Designer Kurtis',
      slug: 'kurti',
      sortOrder: 2,
    ),
    Category(
      id: 3,
      businessId: 1,
      name: 'Dress Materials',
      slug: 'dress-material',
      sortOrder: 3,
    ),
    Category(
      id: 4,
      businessId: 1,
      name: 'Bridal Lehenga',
      slug: 'lehenga',
      sortOrder: 4,
    ),
    Category(
      id: 5,
      businessId: 1,
      name: 'Unstitched Fabric',
      slug: 'fabric',
      sortOrder: 5,
    ),
  ];

  static final List<Product> demoProducts = [
    Product(
      id: 101,
      businessId: 1,
      categoryId: 1,
      categoryName: 'Saree Collection',
      createdByUserId: 1,
      productCode: 'SR-260915-013',
      title: 'Festive Georgette Saree',
      fabric: 'Dola Silk',
      color: 'Emerald Green',
      size: 'Free Size (6.30m with Blouse)',
      occasion: 'Festive',
      festival: 'Diwali Special',
      setCount: 4,
      setLabel: 'Set of 4 Colors',
      brand: 'Surat Silk Exclusive',
      price: 950,
      priceLabel: '₹950 / Pc (Set of 4)',
      costPrice: 650,
      stockStatus: 'available',
      stockQuantity: 180,
      shortDescription:
          'Heavy Zari weaving work on Dola silk with contrast jacquard border. 4 matching festive colors.',
      internalNotes: 'Mill Lot #442. High moving Diwali special.',
      isPublic: true,
      isActive: true,
      viewsCount: 342,
      inquiriesCount: 28,
      colorVariants: [
        'Emerald Green',
        'Wine / Purple',
        'Rani Pink',
        'Royal Blue',
      ],
      imageUrls: [
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop&q=80',
      ],
      media: [
        MediaAsset(
          id: 1,
          businessId: 1,
          productId: 101,
          originalPath:
              'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
          watermarkedPath:
              'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
          thumbnailPath:
              'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=300&auto=format&fit=crop&q=80',
          mimeType: 'image/jpeg',
          fileSizeBytes: 1200000,
        ),
      ],
    ),
    Product(
      id: 102,
      businessId: 1,
      categoryId: 1,
      categoryName: 'Saree Collection',
      createdByUserId: 1,
      productCode: 'SR-260915-012',
      title: 'Festive Georgette Saree',
      fabric: 'Dola Silk',
      color: 'Wine / Purple',
      size: 'Free Size (6.30m)',
      occasion: 'Party Wear',
      festival: 'Navratri & Garba',
      setCount: 4,
      setLabel: 'Set of 4 Colors',
      brand: 'Surat Silk Exclusive',
      price: 950,
      priceLabel: '₹950 / Pc (Set of 4)',
      costPrice: 650,
      stockStatus: 'available',
      stockQuantity: 220,
      shortDescription:
          '60 gram pure georgette fabric with fancy gold foil stamping and embroidered cutwork scallop border.',
      internalNotes: 'Very fast moving for festive season.',
      isPublic: true,
      isActive: true,
      viewsCount: 512,
      inquiriesCount: 46,
      colorVariants: ['Wine / Purple', 'Rani Pink', 'Maroon', 'Mustard Yellow'],
      imageUrls: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80',
      ],
      media: [
        MediaAsset(
          id: 2,
          businessId: 1,
          productId: 102,
          originalPath:
              'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
          watermarkedPath:
              'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
          thumbnailPath:
              'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=300&auto=format&fit=crop&q=80',
          mimeType: 'image/jpeg',
          fileSizeBytes: 1100000,
        ),
      ],
    ),
    Product(
      id: 103,
      businessId: 1,
      categoryId: 1,
      categoryName: 'Saree Collection',
      createdByUserId: 1,
      productCode: 'SR-260915-011',
      title: 'Festive Georgette Saree',
      fabric: 'Dola Silk',
      color: 'Pink / Rani',
      size: 'Free Size',
      occasion: 'Wedding / Bridal',
      festival: 'Wedding Season',
      setCount: 4,
      setLabel: 'Set of 4 Colors',
      brand: 'Surat Silk Exclusive',
      price: 950,
      priceLabel: '₹950 / Pc (Set of 4)',
      costPrice: 650,
      stockStatus: 'available',
      stockQuantity: 140,
      shortDescription:
          'Fancy gold butti weave with contrast Banarasi pallu in rich bridal colors.',
      internalNotes: 'Wedding season best-seller.',
      isPublic: true,
      isActive: true,
      viewsCount: 410,
      inquiriesCount: 35,
      colorVariants: [
        'Pink / Rani',
        'Maroon',
        'Teal / Rama Green',
        'Mustard Yellow',
      ],
      imageUrls: [
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop&q=80',
      ],
      media: [],
    ),
    Product(
      id: 104,
      businessId: 1,
      categoryId: 2,
      categoryName: 'Designer Kurtis',
      createdByUserId: 1,
      productCode: 'SR-260915-010',
      title: 'Rayon 14kg Handwork Anarkali Kurti with Dupatta',
      fabric: 'Rayon 14kg',
      color: 'Peach',
      size: 'Set of All Sizes (S to XXL)',
      occasion: 'Party Wear',
      festival: 'Diwali Special',
      setCount: 4,
      setLabel: 'Set of 4 (Sizes S-XXL)',
      brand: 'Radha Rani',
      price: 650,
      priceLabel: '₹650 / Pc (Set of 4)',
      costPrice: 420,
      stockStatus: 'limited',
      stockQuantity: 45,
      shortDescription:
          'Heavy mirror and thread handwork on neckline, flair 3.5 meters with printed organza dupatta.',
      internalNotes: 'Only 45 pcs remaining in M and XL.',
      isPublic: true,
      isActive: true,
      viewsCount: 290,
      inquiriesCount: 19,
      colorVariants: ['Peach', 'Pista Green', 'Rani Pink', 'Teal'],
      imageUrls: [
        'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
      ],
      media: [],
    ),
    Product(
      id: 105,
      businessId: 1,
      categoryId: 3,
      categoryName: 'Dress Materials',
      createdByUserId: 1,
      productCode: 'SR-260915-009',
      title: 'Jam Cotton Unstitched Suit with Nazneen Dupatta',
      fabric: 'Cotton',
      color: 'Mustard Yellow',
      size: 'Unstitched (2.5m + 2.7m)',
      occasion: 'Daily Wear',
      festival: 'Regular / All Season',
      setCount: 6,
      setLabel: 'Set of 6 Colors',
      brand: 'Surat Fashion Hub',
      price: 520,
      priceLabel: '₹520 / Pc (Set of 6)',
      costPrice: 340,
      stockStatus: 'available',
      stockQuantity: 300,
      shortDescription:
          'Pure Jam cotton top 2.50m, pure cotton bottom 2.70m, Nazneen dupatta with 4 side lace.',
      internalNotes: 'Best seller for daily wear boutiques.',
      isPublic: true,
      isActive: true,
      viewsCount: 180,
      inquiriesCount: 14,
      colorVariants: [
        'Mustard Yellow',
        'Rani',
        'Navy Blue',
        'Maroon',
        'Pista Green',
        'Wine',
      ],
      imageUrls: [
        'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
      ],
      media: [],
    ),
    Product(
      id: 106,
      businessId: 1,
      categoryId: 4,
      categoryName: 'Bridal Lehenga',
      createdByUserId: 1,
      productCode: 'SR-260915-008',
      title: 'Velvet Multi-Sequence Bridal Semi-Stitched Lehenga',
      fabric: 'Velvet',
      color: 'Royal Blue',
      size: 'Semi-Stitched (Up to 44)',
      occasion: 'Wedding / Bridal',
      festival: 'Wedding Season',
      setCount: 1,
      setLabel: 'Single Piece',
      brand: 'Ambaji Creation',
      price: 3850,
      priceLabel: '₹3,850 / Single Piece',
      costPrice: 2400,
      stockStatus: 'available',
      stockQuantity: 35,
      shortDescription:
          '9000 Micro velvet with 5mm tone-to-tone sequence work, double can-can with canvas patta, 4.2m flair.',
      internalNotes: 'Bridal season special.',
      isPublic: true,
      isActive: true,
      viewsCount: 420,
      inquiriesCount: 32,
      colorVariants: ['Royal Blue', 'Maroon', 'Wine'],
      imageUrls: [
        'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
      ],
      media: [],
    ),
  ];

  static final List<Collection> demoCollections = [
    Collection(
      id: 201,
      businessId: 1,
      createdByUserId: 1,
      name: "Today's Daily Drop",
      slug: 'todays-daily-drop',
      description:
          'Exclusive 13 fresh designs in Dola Silk, Georgette & Rayon just launched from Surat factory floor. Ready stock dispatch.',
      collectionDate: DateTime.now(),
      coverMediaUrl:
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
      visibility: 'public',
      priceVisibility: 'show',
      showInMainCatalog: true,
      festival: 'Diwali Special',
      occasion: 'Festive',
      shareToken: 'drop-today-live',
      publishedAt: DateTime.now().subtract(const Duration(hours: 3)),
      expiresAt: DateTime.now().add(const Duration(hours: 21)),
      productIds: [101, 102, 103, 104, 105, 106],
      products: demoProducts,
      viewsCount: 1240,
      inquiriesCount: 86,
    ),
    Collection(
      id: 202,
      businessId: 1,
      createdByUserId: 1,
      name: 'Diwali Festive Silk Special',
      slug: 'diwali-festive-silk-2026',
      description:
          'Premium Banarasi & Dola Silk Jacquard sarees for the grand festive season. Book full catalog sets early.',
      collectionDate: DateTime.now().subtract(const Duration(days: 2)),
      coverMediaUrl:
          'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop&q=80',
      visibility: 'public',
      priceVisibility: 'show',
      showInMainCatalog: true,
      festival: 'Diwali Special',
      occasion: 'Party Wear',
      shareToken: 'diwali-festive-silk',
      publishedAt: DateTime.now().subtract(const Duration(days: 2)),
      expiresAt: DateTime.now().add(const Duration(days: 5)),
      productIds: [101, 102, 103],
      products: [demoProducts[0], demoProducts[1], demoProducts[2]],
      viewsCount: 890,
      inquiriesCount: 54,
    ),
    Collection(
      id: 203,
      businessId: 1,
      createdByUserId: 1,
      name: 'Navratri Chaniya Choli & Kurti Drop',
      slug: 'navratri-garba-special',
      description:
          'Authentic Gamthi & Mirror work kurtis and flare lehengas for Garba nights.',
      collectionDate: DateTime.now().subtract(const Duration(days: 4)),
      coverMediaUrl:
          'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80',
      visibility: 'public',
      priceVisibility: 'show',
      showInMainCatalog: true,
      festival: 'Navratri & Garba',
      occasion: 'Festive',
      shareToken: 'navratri-garba-drop',
      publishedAt: DateTime.now().subtract(const Duration(days: 4)),
      expiresAt: DateTime.now().add(const Duration(days: 3)),
      productIds: [104, 105],
      products: [demoProducts[3], demoProducts[4]],
      viewsCount: 650,
      inquiriesCount: 42,
    ),
  ];

  static final List<Contact> demoContacts = [
    Contact(
      id: 301,
      businessId: 1,
      name: 'Pooja Sharma',
      phoneE164: '+919876543210',
      companyName: 'Riya Boutique',
      city: 'Ahmedabad',
      state: 'Gujarat',
      contactType: 'boutique',
      preferredLanguage: 'gu',
      tags: ['Regular Buyer', 'Silk Sarees', 'Prompt Payment'],
      totalInquiries: 12,
      totalOrders: 4,
    ),
    Contact(
      id: 302,
      businessId: 1,
      name: 'Manish Agarwal',
      phoneE164: '+919811122334',
      companyName: 'Agarwal Saree Sadan',
      city: 'Jaipur',
      state: 'Rajasthan',
      contactType: 'dealer',
      preferredLanguage: 'hi',
      tags: ['Wholesaler', 'Georgette Bulk'],
      totalInquiries: 18,
      totalOrders: 9,
    ),
    Contact(
      id: 303,
      businessId: 1,
      name: 'Sunita Reddy',
      phoneE164: '+919944556677',
      companyName: 'Sri Lakshmi Silks',
      city: 'Hyderabad',
      state: 'Telangana',
      contactType: 'reseller',
      preferredLanguage: 'en',
      tags: ['Reseller', 'WhatsApp Catalog'],
      totalInquiries: 8,
      totalOrders: 2,
    ),
  ];

  static final List<Inquiry> demoInquiries = [
    Inquiry(
      id: 401,
      businessId: 1,
      contactId: 301,
      contactName: 'Pooja Sharma',
      contactPhone: '+919876543210',
      contactCompany: 'Riya Boutique',
      productId: 101,
      productCode: 'SR-260915-013',
      productTitle: 'Festive Georgette Saree',
      productImage:
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&auto=format&fit=crop&q=80',
      productPrice: 950,
      collectionId: 201,
      collectionName: "Today's Daily Drop",
      assignedToUserId: 2,
      assignedToUserName: 'Amit Shah',
      source: 'catalog',
      status: 'new',
      message:
          'Please send video and available 4 colors in this Dola silk design. Ready to book 2 full sets.',
      quotedAmount: 7600,
      nextFollowUpAt: DateTime.now().add(const Duration(hours: 4)),
      activities: [
        InquiryActivity(
          id: 1,
          businessId: 1,
          inquiryId: 401,
          activityType: 'created',
          body: 'Inquiry received via WhatsApp link for Design SR-260915-013.',
          createdAt: DateTime.now().subtract(const Duration(minutes: 35)),
        ),
      ],
    ),
  ];
}
