-- TextileDrop MySQL Migration 002: Business Settings, Categories, Products, Collections, Media

CREATE TABLE IF NOT EXISTS business_settings (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NOT NULL UNIQUE,
    catalog_title VARCHAR(150) NULL,
    catalog_description TEXT NULL,
    default_currency CHAR(3) NOT NULL DEFAULT 'INR',
    show_prices_publicly TINYINT(1) NOT NULL DEFAULT 1,
    allow_guest_inquiry TINYINT(1) NOT NULL DEFAULT 1,
    watermark_enabled TINYINT(1) NOT NULL DEFAULT 1,
    watermark_text VARCHAR(120) NULL,
    inquiry_whatsapp_template TEXT NULL,
    terms_url VARCHAR(500) NULL,
    privacy_url VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_settings_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NOT NULL,
    parent_id BIGINT UNSIGNED NULL,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL,
    UNIQUE KEY uq_category_business_slug (business_id, slug),
    INDEX idx_category_business_active (business_id, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collections (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NOT NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    description TEXT NULL,
    collection_date DATE NULL,
    cover_media_id BIGINT UNSIGNED NULL,
    visibility ENUM('draft','public','private','archived') NOT NULL DEFAULT 'public',
    price_visibility ENUM('inherit','show','hide','on_request') NOT NULL DEFAULT 'inherit',
    show_in_main_catalog TINYINT(1) NOT NULL DEFAULT 1,
    festival VARCHAR(100) NULL,
    occasion VARCHAR(100) NULL,
    share_token CHAR(36) NOT NULL UNIQUE,
    published_at DATETIME NULL,
    expires_at DATETIME NULL,
    sort_order INT NOT NULL DEFAULT 0,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_collection_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    CONSTRAINT fk_collection_user FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    UNIQUE KEY uq_collection_business_slug (business_id, slug),
    INDEX idx_collection_public (business_id, visibility, published_at, show_in_main_catalog),
    INDEX idx_collection_date (business_id, collection_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NULL,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    product_code VARCHAR(80) NOT NULL,
    title VARCHAR(180) NULL,
    fabric VARCHAR(100) NULL,
    color VARCHAR(100) NULL,
    size VARCHAR(100) NULL,
    occasion VARCHAR(100) NULL,
    festival VARCHAR(100) NULL,
    set_count INT NOT NULL DEFAULT 4,
    set_label VARCHAR(100) NULL,
    brand VARCHAR(100) NULL,
    price DECIMAL(12,2) NULL,
    price_label VARCHAR(100) NULL,
    cost_price DECIMAL(12,2) NULL,
    stock_status ENUM('available','limited','sold_out','discontinued') NOT NULL DEFAULT 'available',
    stock_quantity INT NULL,
    short_description VARCHAR(500) NULL,
    internal_notes TEXT NULL,
    is_public TINYINT(1) NOT NULL DEFAULT 1,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_product_user FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    UNIQUE KEY uq_product_business_code (business_id, product_code),
    INDEX idx_product_search (business_id, product_code, stock_status, is_active),
    INDEX idx_product_category (business_id, category_id),
    INDEX idx_product_fabric (business_id, fabric),
    INDEX idx_product_color (business_id, color),
    INDEX idx_product_festival (business_id, festival),
    INDEX idx_product_occasion (business_id, occasion)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS collection_products (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NOT NULL,
    collection_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cp_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    CONSTRAINT fk_cp_collection FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE,
    CONSTRAINT fk_cp_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    UNIQUE KEY uq_collection_product (collection_id, product_id),
    INDEX idx_cp_collection_sort (collection_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS media_assets (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    business_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NULL,
    collection_id BIGINT UNSIGNED NULL,
    uploaded_by_user_id BIGINT UNSIGNED NOT NULL,
    media_type ENUM('image','video','pdf') NOT NULL DEFAULT 'image',
    original_filename VARCHAR(255) NULL,
    storage_disk VARCHAR(50) NOT NULL DEFAULT 'local',
    original_path VARCHAR(500) NOT NULL,
    optimized_path VARCHAR(500) NULL,
    thumbnail_path VARCHAR(500) NULL,
    watermarked_path VARCHAR(500) NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size_bytes BIGINT UNSIGNED NOT NULL,
    width INT NULL,
    height INT NULL,
    duration_seconds INT NULL,
    processing_status ENUM('pending','processing','ready','failed') NOT NULL DEFAULT 'ready',
    processing_error TEXT NULL,
    alt_text VARCHAR(255) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_media_business FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE,
    CONSTRAINT fk_media_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_media_collection FOREIGN KEY (collection_id) REFERENCES collections(id) ON DELETE CASCADE,
    CONSTRAINT fk_media_user FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id),
    INDEX idx_media_product (business_id, product_id, sort_order),
    INDEX idx_media_collection (business_id, collection_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
